config/routes.rb
BetaInvites::Engine.routes.draw do
  resources :beta_requests do
    member do
      post "send_invite"
    end
  end

  root to: "beta_requests#index"

end

app/models/beta_invites/beta_request.rb
module BetaInvites
  class BetaRequest < ActiveRecord::Base
    require 'valid_email'

    belongs_to :user, class_name: BetaInvites.user_class
    belongs_to :invited_by, :class_name => "User", :foreign_key => "invited_by"
    validates :email, :presence=>{:message=>"You must enter a valid email address!"}, :email=> true, 
      :uniqueness=>{:message=>"has already been used to request an invite"}
    validate :not_already_registered, :on => :create

    USER_CLASS = BetaInvites.user_class

    # after_create :identify_for_analytics
    def send_invite!
      email = self.email
      user = USER_CLASS.new(email: email)
      # username validation isn't skipped...figure out how to skip this?
      if user.attributes.keys.include?("username")
        user.username = set_username_from(email)
      end
      if mail = user.invite!
        user = User.find_by(email: mail.to.first) # the newly created user from #invite!
        
        user.name = self.name if user.attributes.keys.include?("name") && self.name.present?         
        self.invite_sent = true
        self.invite_sent_at = Time.now
        self.user_id = user.id # id of new user being created
        self.save
        user.save
        # Setting the new user as a creator.
      else
        puts "Could not create invite..."
      end
      return user
    end


  private

    def not_already_registered
      if user=USER_CLASS.find_by(email: email)
        errors.add :email, "is already registered. Use the links below to login."
      end
      
    end

    # generates a unique username given a base name
    def set_username_from(name)
      n = 0
      new_name = name
      while USER_CLASS.where("username = ?", new_name).present? do
        n+=1
        new_name = "#{name.split("@")[0]}#{n}" # accounts for emails and normal strings
      end
      new_name
    end

  end
end

app/controllers/beta_invites/application_controller.rb
module BetaInvites
  class ApplicationController < ActionController::Base
  end
end

app/controllers/beta_invites/beta_requests_controller.rb
require_dependency "beta_invites/application_controller"

module BetaInvites
  class BetaRequestsController < ApplicationController
    before_action :set_beta_request, only: [:new, :show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:index]

    # GET /beta_requests
    def index
      @beta_requests = BetaRequest.all
    end

    # GET /beta_requests/1
    def show
    end

    # GET /beta_requests/new
    def new
    end

    # GET /beta_requests/1/edit
    def edit
    end

    # POST /beta_requests
    def create
      @beta_request = BetaRequest.new(beta_request_params)

      # you can enable users to invite new users. Track that here:
      if user_signed_in?
        @beta_request.invited_by = current_user
      end

      if @beta_request.save        
        # mailers should be in main app        
        redirect_to main_app.root_url, notice: 'Beta request was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /beta_requests/1
    def update
      if @beta_request.update(beta_request_params)
        redirect_to @beta_request, notice: 'Beta request was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /beta_requests/1
    def destroy
      @beta_request.destroy
      redirect_to beta_requests_url, notice: 'Beta request was successfully destroyed.'
    end

    # POST from beta_requests#idnex, to be used by admins to fire off invites
    def send_invite
      invitee=BetaInvites::BetaRequest.find(params[:id])
      user = invitee.send_invite!
      invitee.user.update_attributes({:invited_by_id=>current_user.id}) rescue nil
      user.is_a?(BetaInvites.user_class) ? flash[:notice] = "Invite sent!" : flash[:notice] = "Could not create user..."
      respond_to do |format|
        format.html {redirect_to root_url}
      end
    end
    
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_beta_request
        @beta_request = BetaRequest.find(params[:id]) if params[:id]
        unless @beta_request
          @beta_request = BetaRequest.new(email: params[:email])
        end
      end

      # Only allow a trusted parameter "white list" through.
      def beta_request_params
        params.require(:beta_request).permit(:name, :city, :state, :zip, :country, :user_id, :invite_sent, :invitation_token, :invited_by, :invite_sent_at, :email, :kind, :comments)
      end
  end
end

app/helpers/beta_invites/application_helper.rb
module BetaInvites
  module ApplicationHelper
  end
end

app/helpers/beta_invites/beta_requests_helper.rb
module BetaInvites
  module BetaRequestsHelper
  end
end

app/views/beta_invites/beta_requests/_form.html.erb
<%= form_for(@beta_request) do |f| %>
  <% if @beta_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beta_request.errors.count, "error") %> prohibited this beta_request from being saved:</h2>

      <ul>
      <% @beta_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>


  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beta_invites/beta_requests/edit.html.erb
<h1>Editing beta_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @beta_request %> |
<%= link_to 'Back', beta_requests_path %>

app/views/beta_invites/beta_requests/index.html.erb
<h1>Listing beta_requests</h1>
<table class="datatable" data-sort="6">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Email</th>      
      <th>Kind</th>
      <th>Comments</th>
      <th>Invited By</th>
      <th>Send Invite</th>
      <th>Accepted?</th>
      <th>Created At</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @beta_requests.each do |beta_request| %>
      <tr>
        <td><%=beta_request.name%></td>
        <td><%= beta_request.city %></td>
        <td>
          <%= beta_request.email %>
        </td>

        <td>
          <%= beta_request.kind %>
        </td>
        <td>
          <%= beta_request.comments %>
        </td>
        <% if user = beta_request.user  %>
          <% invite_text = link_to "Sent at #{user.invitation_sent_at}", "javascript:alert('Link: /users/invitation/accept?invitation_token=#{user.invitation_token}');"  %>
          <% if user.invitation_accepted_at %>
            <% accepted_text = "#{user.invitation_accepted_at.strftime("%Y/%m/%e %H:%M")}" %>
          <% else %>
            <% accepted_text = "0" %>
          <% end %>
        <% else %>
          <% invite_text = button_to "send invite", send_invite_beta_request_path(beta_request) %>
        <% end %>
        <% if beta_request.invited_by.nil? %>
          <td>Request form</td>
        <% else %>
          <td>
            <%= beta_request.invited_by.email %>
          </td>
        <% end %>
        <td>
          <%= invite_text %>
        </td>
        <td>
          <%= accepted_text if defined?(accepted_text)  %>
        </td>
        <td>
          <%= beta_request.created_at.strftime("%Y/%m/%e %H:%M ") %>
        </td>
        <td>
          <%= link_to 'Edit', edit_beta_request_path(beta_request) %>
        </td>
        <td>
          <%= link_to 'Destroy', beta_request, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Beta Request', new_beta_request_path %>

app/views/beta_invites/beta_requests/new.html.erb
<h1>New beta_request</h1>

<%= render 'form' %>

<%= link_to 'Back', beta_requests_path %>

app/views/beta_invites/beta_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @beta_request.user_id %>
</p>

<p>
  <strong>Invite sent:</strong>
  <%= @beta_request.invite_sent %>
</p>

<p>
  <strong>Invitation token:</strong>
  <%= @beta_request.invitation_token %>
</p>

<p>
  <strong>Invited by:</strong>
  <%= @beta_request.invited_by %>
</p>

<p>
  <strong>Invite sent at:</strong>
  <%= @beta_request.invite_sent_at %>
</p>

<p>
  <strong>Email:</strong>
  <%= @beta_request.email %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @beta_request.kind %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @beta_request.comments %>
</p>

<%= link_to 'Edit', edit_beta_request_path(@beta_request) %> |
<%= link_to 'Back', beta_requests_path %>

app/views/layouts/beta_invites/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BetaInvites</title>
  <%= stylesheet_link_tag    "beta_invites/application", media: "all" %>
  <%= javascript_include_tag "beta_invites/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>